### ISSUE TITLE
fullGetHilltopData()   Error and not returning a dataframe when given invalid site name

### ISSUE THREAD

**Issue by barnardJ** [jeffcnz/hillr#1]
When using fullGetHilltopData(),  providing the sites argument with a string vector containing a string that is not a valid request-able site, will result in an error and no data frame returned.  Even if you have other valid sites in the sites vector.

![githubIssue](https://user-images.githubusercontent.com/47586540/54152201-88f9b380-44a1-11e9-88a3-1bd5f63e3de5.png)

`
library(hillr)

wSites<- c("Waiiti Stream at Waihau Road","Waihau Stream at Waihau Road","Mohaka River D/S Ripia River","TEST1")
wMeasurements <- c("Total Nitrogen", "Turbidity (Field)","Total Phosphorus")

webService <- "http://data.hbrc.govt.nz/Envirodata/EMARtest.hts?"
  
requestData <- fullGetHilltopData(endpoint = webService, sites = wSites, measurements = wMeasurements, option = "WQ") 
 `

In the above code, "TEST1" is not a valid site to request.

Producing:

"Error in subset.default(wqSampDf, select = -c(Site, Measurement, Units)) : 
  argument "subset" is missing, with no default"

**Comment by jeffcnz** [comment]
commit fa4615e76c6778ca2e6bbf2b4cd264014cf440c7 addresses fixes the bug
